### ISSUE TITLE
include option handleOnLoad in Readme.md

### ISSUE THREAD

**Issue by goldensunliu** [KyleAMathews/react-retina-image#2]
I noticed I can pass into custom handleOnLoad from the options
https://github.com/KyleAMathews/react-retina-image/blob/master/src/index.cjsx#L93
if you want I can edit the usage of it in the readme

**Comment by KyleAMathews** [comment]
Hmm... the name is actually wrong :\ it should be `onLoad` not `handleOnLoad`. I'll make the change to the name + add a mention in the readme.

**Comment by KyleAMathews** [comment]
Released 1.2.0
