### ISSUE TITLE
`forceOriginalDimensions` doesn't work with React < v0.14

### ISSUE THREAD

**Issue by tlrobinson** [KyleAMathews/react-retina-image#27]
Versions of React prior to v0.14 require that you call `React.findDOMNode(this.refs.img)` to get the actual DOM element.

It would be nice if react-retina-image supported at least one previous release of React.

**Comment by KyleAMathews** [comment]
[2.0.0 was released to support React 0.14](https://github.com/KyleAMathews/react-retina-image/releases/tag/v2.0.0). If you need support for older versions of React, use the 1.x series.

**Comment by tlrobinson** [comment]
Ok thanks. Would be nice if this were in the readme.

**Comment by KyleAMathews** [comment]
Could you make a quick PR to add that?
