### ISSUE TITLE
Available props: doesn't include src

### ISSUE THREAD

**Issue by DelvarWorld** [KyleAMathews/react-retina-image#3]
https://github.com/KyleAMathews/react-retina-image/blame/master/README.md#L14

    <RetinaImage
       src={["./images/balloon.jpg", "./images/bigger-balloon.jpg]} />

undocumented behavior?

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by DelvarWorld** [comment]
"string or array for the image srcs" - sorry for not making a PR for this - easier to comment for now - but you still haven't explained what an array means.

**Comment by KyleAMathews** [comment]
Hmm... true. It's actually documented (with examples) on the demo page so I added a bit to the README pointing people there: https://github.com/KyleAMathews/react-retina-image/commit/d1c636297f5951c66ae8f96d0c313457d8f36523
