### ISSUE TITLE
React.Spread is deprecated in react 15 and newer

### ISSUE THREAD

**Issue by devjunkORG** [KyleAMathews/react-retina-image#53]
I was going to fix this myself but I've never used .csjx before, I would not know where to start. It should be an easy fix though.

As of right now I'm getting the following warning:

`Warning: React.__spread is deprecated and should not be used. Use Object.assign directly or another helper function with similar semantics. You may be seeing this warning due to your compiler. See https://fb.me/react-spread-deprecation for more details.`

**Comment by KyleAMathews** [comment]
Thanks for bringing this up. I just needed to upgrade coffee-react to 5.0 which fixes this and republish. 2.0.1 is out and shouldn't have this warning any longer.

**Comment by devjunkORG** [comment]
Thanks!

**Comment by devjunkORG** [comment]
I'm still getting the same warning after updating to 2.0.1. Have you tested the new build?

**Comment by KyleAMathews** [comment]
I just looked at the compiled code and there's no React.__spread to be found so I'm assuming your update didn't work. Check what code you have in `node_modules`.

**Comment by devjunkORG** [comment]
You were right, for some reason the update didn't work the first 10 times. Thanks :)

**Comment by KyleAMathews** [comment]
Deleting node_modules and reinstalling often helps :-)

**Comment by devjunkORG** [comment]
Yeah, I did that. `npm cache clean` did the trick in the end.
