### ISSUE TITLE
Fix react 15.2 warning about Unknown props on DOM

### ISSUE THREAD

**Issue by morajabi** [KyleAMathews/react-retina-image#61]

**Comment by alexcris** [comment]
is there a fix yet for this issue? @KyleAMathews

**Comment by alexcris** [comment]
@morajabi did you find a way to avoid this warning?

**Comment by FredyC** [comment]
Well obvious way is to remove props that are introduced for Retina component itself alone before passing to the actual image. I agree it should be fixed, it's annoying to dig through unnecessary warnings.

**Comment by morajabi** [comment]
For example instead of 
`<Component {...this.props} />`
Do
```
const { customProps, anotherCustomProps, ...otherPassedProps } = this.props;
<Component {...otherPassedProps} />
```

**Comment by 40818419** [comment]
```
Warning: Unknown props 'checkIfRetinaImgExists', 'forceOriginalDimensions', 'retinaImageSuffix', 'srcIsArray' on <img> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in img (created by RetinaImage)
```
any progress there?

**Comment by KyleAMathews** [comment]
Hey folks — I'm really busy right now working on [Gatsby](https://github.com/gatsbyjs/gatsby). If one of you could put together a PR I'd be happy to review it and merge it.

**Comment by sompylasar** [comment]
@KyleAMathews The PR: https://github.com/KyleAMathews/react-retina-image/pull/71

Please review, merge and release. Thanks!

**Comment by electic** [comment]
Any updates on this?

**Comment by electic** [comment]
Thank you @KyleAMathews!
