### ISSUE TITLE
React.createClass is deprecated in React v15.5.0

### ISSUE THREAD

**Issue by tlrobinson** [KyleAMathews/react-retina-image#78]
> warning.js?a63b:40 Warning: RetinaImage: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by KyleAMathews** [comment]
Would love a PR to fix this. I'm not actively maintaining it right now but
will merge a fix and make a new release.

**Comment by tlrobinson** [comment]
@KyleAMathews What's your preference:

1. ship the ES6 class
2. add a `prepublish` script to compile it with babel
3. add the `create-react-class` dependency and use that
