### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by iLeonelPerea** [KyleAMathews/react-retina-image#81]
Hi.. 

I am seeign two errors in console.. here the images.

Here my code:

<RetinaImage
   src={["../imgs/how-does-it-work-1.jpg","../imgs/how-does-it-work-1_2x.jpg"]}
/>

<img width="1124" alt="screen shot 2017-05-23 at 2 39 54 pm" src="https://cloud.githubusercontent.com/assets/2968628/26373168/1b9239d4-3fc6-11e7-8042-c2c927af64ad.png">
<img width="1426" alt="screen shot 2017-05-23 at 2 39 18 pm" src="https://cloud.githubusercontent.com/assets/2968628/26373167/1b8b1d66-3fc6-11e7-99ed-b386ca24b491.png">

I can help with a pull request.. but i need to understand some code..

```
el = this.refs.img;
    if (!el.complete) {
      return false;
    }
    if (el.naturalWidth === 0) {
      return false;
    }
```

Where you define complete and naturalWidth?

I saw the state retinaCheckComplete maybe could be used instead of complete.... Or you could explain me the implementation required to help you.

**Comment by KyleAMathews** [comment]
From the second error, it seems you have multiple copies of React loaded which is almost certainly what's causing the trouble. `el` here is the DOM element for the image this component is managing.
